name: CD
on:
  push:
    branches:
      - main
      - dev
      - CDCI
    tags:
      - 'v*'

jobs:
  dockerProd:
    if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push'}}
    name: Build and push Docker images 
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        dockerfile: ['develop']
   
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: fafago
          password: ${{ secrets.DOCKER_REGISTRY_PASS }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: fafagoreviews/reviews:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}  
  dockerDev:
    if: ${{ github.ref == 'refs/heads/dev' && github.event_name == 'push'}}
    name: Build and push Docker images 
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        dockerfile: ['develop']
   
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: fafago
          password: ${{ secrets.DOCKER_REGISTRY_PASS }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: fafagoreviews/reviews:dev
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}  
