name: CD
on:
  push:
    branches:
      - main
      - dev
      - CDCI
    tags:
      - 'v*'

jobs:
  docker:
    name: Build and push Docker images 
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        dockerfile: ['develop']
   
    steps:
    - name: Build Docker image
      uses: docker/build-push-action@v1.1.0
      with:
        username: fafagosoftware
        password: ${{ secrets.DOCKER_REGISTRY_PASS }}
        repository: fafago/governify-web
        tags: latest
        tag_with_ref: true
        tag_with_sha: true 
        # Path to the Dockerfile (Default is '{path}/Dockerfile')
        dockerfile: 'Dockerfile'
        always_pull: false
        cache_froms: node:buster-slim
        add_git_labels: true
        push: true # optional, default is true 
