name: CI
on:
  push:
    branches:
      - master
      - dev
    tags:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test using Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: npm install --also=dev
      - run: npm test
      - name: Tests ✅
        if: ${{ success() }}
        run: |
          curl --request POST           --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }}           --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}'           --header 'content-type: application/json'           --data '{
            "context": "tests",
            "state": "success",
            "description": "Tests passed",
            "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'
      - name: Tests 🚨
        if: ${{ failure() }}
        run: |
          curl --request POST           --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }}           --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}'           --header 'content-type: application/json'           --data '{
            "context": "tests",
            "state": "failure",
            "description": "Tests failed",
            "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'

  cleanup-runs:
    runs-on: ubuntu-latest
    steps:
    - uses: rokroskar/workflow-run-cleanup-action@master
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        
  lint:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - name: eslint
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review # Change reporter.
          eslint_flags: 'src/'
      - name: Dockerfile
        uses: reviewdog/action-hadolint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review # Default is github-pr-check
          level: warning

  docker:
    name: Build Docker images 
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: true
      matrix:
        dockerfile: ['Dockerfile.develop']
   
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Build Docker image
      uses: docker/build-push-action@v1.1.0
      with:
        username: isagroup
        password: ${{ secrets.DOCKER_REGISTRY_PASS }}
        repository: isagroup/governify-web
        tags: latest
        tag_with_ref: true
        tag_with_sha: false 
        # Path to the Dockerfile (Default is '{path}/Dockerfile')
        dockerfile: docker/${{ matrix.dockerfile }}
        always_pull: false
        cache_froms: node:buster-slim
        add_git_labels: true
        push: false # optional, default is true 
